name: flask_tensorflow
dependencies:
- conda-forge::mock=2.0.0=py35_0
- conda-forge::pbr=1.10.0=py35_0
- conda-forge::protobuf=3.1.0=py35_0
- conda-forge::six=1.10.0=py35_1
- conda-forge::tensorflow=0.12.1=py35_1
- click=6.6=py35_0
- flask=0.11.1=py35_0
- gunicorn=19.1.0=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_1
- markupsafe=0.23=py35_2
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pastedeploy=1.5.2=py35_1
- pip=9.0.1=py35_1
- python=3.5.2=0
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- werkzeug=0.11.11=py35_1
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3


